# image:
#   file: .gitpod.dockerfile

tasks:
  - init: |
      npm install -g npm@latest
      npm install
    
    command: npm run css-watch

  - init: |
      sudo apt-get update
      sudo apt-get install mysql-server -y
      sudo service mysql start
      sudo mysql -e "CREATE USER 'techgear'@'localhost'"
      composer install
      
    command: |
      mysql -u techgear -e "CREATE DATABASE online_store"
      export APP_ENV=PRODUCTION
      export DB_USER=techgear
      export DB_DATABASE=online_store
      vendor/bin/migrate reset --path=. mysql://techgear@localhost/online_store --yes
      php -S 0.0.0.0:8080 -t public

    # env:
    #   APP_ENV: PRODUCTION
    #   DB_DATABASE: online_store

ports:
  - port: 3306
    onOpen: ignore

  - port: 8080
    onOpen: open-browser
