image:
  file: .gitpod.dockerfile

tasks:
  - init: |
      mysql -e "CREATE DATABASE online_store;"
      composer install
      vendor/bin/migrate reset --path=. mysql://root@localhost/online_store --yes
      export APP_ENV=PRODUCTION
      export DB_DATABASE=online_store
    command: php -S 0.0.0.0:8080 -t public

  - init: |
      npm install -g npm@latest
      npm install
    
    command: npm run css-watch

ports:
  - port: 8080
    onOpen: open-browser
