image:
  file: .gitpod.dockerfile

tasks:
  - command: | 
      npm install -g npm@latest
      npm install
      npm run css-watch

  - init: |
      composer install
      
    command: |
      sudo service mysql start
      sudo mysql -e "CREATE USER 'techgear'@'localhost'"
      sudo mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'techgear'@'localhost'"
      sudo mysql -e "FLUSH PRIVILEGES;"
      mysql -u techgear -e "CREATE DATABASE online_store"
      export APP_ENV=PRODUCTION
      export DB_USER=techgear
      export DB_DATABASE=online_store
      vendor/bin/migrate reset --path=. mysql://techgear@localhost/online_store --yes
      php -S 0.0.0.0:8080 -t public

    # env:
    #   APP_ENV: PRODUCTION
    #   DB_DATABASE: online_store

ports:
  - port: 3306
    onOpen: ignore

  - port: 8080
    onOpen: open-browser

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false