name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          git config user.name lenard123
          git config user.email lenard.mangayayam@gmail.com
          git checkout -b production
      - run: npm ci
      - run: npm run prod
      - run: |
          git add .
          git commit -m "Build Assets"
          git push --set-upstream origin production --force