name: Merge Main Branch to Production Branch

on:
  push:
    branches: [main]
    paths: 
      - '**.js'
      - '**.css'
      - '**.php'
      - 'admin/**'
      - 'api/**'
      - 'assets/**'
      - 'storage/**'
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: overtrue/phplint@8.0
        with:
          path: .
          options: --exclude=*.log
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          git config user.name lenard123
          git config user.email lenard.mangayayam@gmail.com
          git checkout -b production
          npm ci
          npm run css-prod
          cp api/config.production.php api/config.php
      - run: |
          git add .
          git commit -m "Use Production config and Build Tailwind CSS"
          git push --set-upstream origin production --force