name: Check if the pull request pass the test

on:
  pull_request:
    branches: [main]
    paths:
      - '**.php'

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: overtrue/phplint@8.0
        with:
          path: .
          options: --exclude=*.log